spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/habit_app
    username: habit_app
    password: 1234
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

security:
  jwt:
    secret: SECRETKEY
    expirationMinutes: 5